package com.mevi.lasheslam.core

object Strings {
    const val appName = "LashesLam"
    const val welcome = "¡Bienvenida!"
    const val login = "Iniciar sesión"
    const val register = "Registrarse"
    const val continueWith = "  Continuar con  "
    const val google = "Google"
    const val logoContentDescription = "Logo LashesLam"
    const val createAccount = "Crear cuenta"
    const val fullName = "Nombre completo"
    const val email = "Correo electrónico"
    const val emailHint = "Correo"
    const val password = "Contraseña"
    const val showHidePassword = "Mostrar/Ocultar contraseña"
    const val confirmPassword = "Confirmar contraseña"
    const val phoneNumber = "Teléfono"
    const val registerButton = "Registrar"
    const val cancelButton = "Cancelar"
    const val appNameByCreator = "LashesLam by Mevi"
    const val access = "Acceder"
    const val loginWithGoogle = "Acceder con Google"
    const val keyRemoteConfigListAdmin = "list_admin"
    const val keyRemoteConfigWhatsappAdmin = "whatsapp_administrador"
    const val defaultAdminWhatsapp = "5514023853"
    const val logErrorProcessingAdminList = "Error al procesar list_admin"
    const val logErrorFetchingRemoteConfig = "Error al obtener Remote Config"
}
